// import 'package:flutter/material.dart';
// import 'package:provider/provider.dart';
// import 'package:thefilms/states/main_app_state.dart';
// import 'package:thefilms/utils/file_manager.dart' as file;
// // import 'package:thefilms/utils/file_manager.dart';
// import 'package:thefilms/utils/navi.dart' as navi;
// import 'package:thefilms/utils/scroll_top_with_controller.dart' as scrollTop;
// import 'package:thefilms/utils/toast_alert.dart' as alert;
// import 'package:thefilms/widgets/custom_loading_spin_kit_ring.dart';
// import 'package:thefilms/widgets/movie_card.dart';
// import 'package:thefilms/widgets/movie_card_container.dart';
// import 'package:thefilms/widgets/shadowless_floating_button.dart';
// import 'package:sizer/sizer.dart';
// import 'package:cached_network_image/cached_network_image.dart';
// import 'package:flutter/rendering.dart';
// import 'package:thefilms/utils/star_calculator.dart'
//     as starCalculator;
// import 'package:thefilms/widgets/colored_circle.dart';
// import 'package:thefilms/model/preview_model.dart';
// import 'package:thefilms/secret/themoviedb_api.dart' as secret;
// import 'services/networking.dart';
// import 'package:thefilms/screens/splash_screen.dart';
// import 'package:path_provider/path_provider.dart';
// import 'dart:io';


// part 'main.dart';
// part 'model/details_model.dart';
// part 'utils/constants.dart';
// part 'utils/file_manager.dart';
// part 'services/movie.dart';
// part 'services/tv.dart';
// part 'screens/home_screen.dart';
// part 'screens/details_tv_screen.dart';
// part 'screens/details_movies_screen.dart';
// part 'screens/finder_screen.dart';
// part 'screens/drawer_screen.dart';
// part 'widgets/bottom_navigation_item.dart';
// part 'widgets/bottom_navigation.dart';
// part 'widgets/custom_main_appbar_content.dart';
// part 'widgets/custom_movies_button.dart';
// part 'widgets/custom_search_appbar_content.dart';
// part 'widgets/drawer_item.dart';
